### ISSUE TITLE
[Bug report] 高级过滤器的文本框输入字符后失焦

### ISSUE THREAD

**Issue by dango0911** [kongying-tavern/map_register_v3#125]
### 错误页面的链接

正式环境

### 重现步骤

对于高级过滤器中需要使用到文本框的部分功能，其光标会在 **每新输入一个字符后** 自动消失，每次都需要重新点击文本框聚焦以继续输入（Bug 疑似与元素拖拽相关）

![Before](https://github.com/kongying-tavern/map_register_v3/assets/136219616/604373ee-55ef-41b2-aabb-1e581cc0bd71)
![After](https://github.com/kongying-tavern/map_register_v3/assets/136219616/9ae17361-18e7-43dd-a184-e701885a71ae)

### 浏览器版本

Microsoft Edge 126.0.2592.68

### 系统版本

Windows 11 (23H2)

**Comment by Altermoe** [comment]
已确认此问题，正在处理。

**Comment by Altermoe** [comment]
## 进度
已修复于 [Commit(dev) 94f37da8](https://github.com/kongying-tavern/map_register_v3/commit/94f37da863ae659fda8078e4eb7ba7a04e1a5e78)

## 定位问题
`conditionComposed` 在每次数据更新后都生成了新的 key，该 key 是组件 `AppDraggableTable` 用于渲染子组件的标识，key 变更后导致子组件重新渲染，造成文档 focus 状态丢失。

## 修复思路
将 key 的生成移动到此配置项的创建阶段而非响应式计算阶段。
