### ISSUE TITLE
[Bug report] 拖动多选文本与过滤条目拖拽冲突

### ISSUE THREAD

**Issue by dango0911** [kongying-tavern/map_register_v3#126]
### 错误页面的链接

正式环境

### 重现步骤

对于含有文本框的过滤条目，在 textbox 范围内拖动多选文本会优先触发该过滤条目的 dragstart，无法拖动选中文本

### 期望结果

对于含有 textbox 的过滤条目，其 dragstart 行为的触发应分为下列几种情况：
**此触发仅在 textbox 范围外起效**

参考逻辑：
开始拖动动作时：
- 页面焦点位于 textbox 上：此时拖动动作应以 `拖动多选文本` 为主
  - 若拖动的起始位置在 textbox 范围 **外**，视作拖动该过滤条目，textbox 失焦，触发 dragstart；
  - 若拖动的起始位置在 textbox 范围 **内**，视作拖动其内的文本，不触发 dragstart；
- 页面焦点不在 textbox 上：此时拖动动作应以 `拖动过滤条目` 为主
  - 拖动的起始位置位于过滤条目范围外：不作处理；
  - 拖动的起始位置位于过滤条目范围内，但位于 textbox 范围外：视作拖动该过滤条目，触发 dragstart；
  - 拖动的起始位置位于 textbox 范围内：不触发 dragstart，也不视作拖动选中其内的文本，但将页面焦点置于 textbox 上。

### 实际结果

在 textbox 范围内拖动多选文本会优先触发该过滤条目的 dragstart，无法拖动选中文本

### 浏览器版本

Microsoft Edge 126.0.2592.68

### 系统版本

Windows 11 (23H2)

**Comment by Altermoe** [comment]
已确认此问题，正在处理。

**Comment by Altermoe** [comment]
## 进度
已修复于 [Commit(dev) 294e2b4d](https://github.com/kongying-tavern/map_register_v3/commit/294e2b4d2665663c5701f4dbd2a2261effe24618)

## 定位问题
input 元素的父元素上存在 draggable="true" 属性，导致其选中操作被拖拽操作覆盖。

## 修复思路
不再常驻 draggable="true" 属性，改为在 pointerdown 时判断事件发生源是否为 input 元素来动态的设定 draggable 的值。
