### ISSUE TITLE
[Bug report] 部分特殊的点位刷新时间在点位弹窗内显示为“不刷新”

### ISSUE THREAD

**Issue by dango0911** [kongying-tavern/map_register_v3#130]
### 错误页面的链接

Dev 环境

### 重现步骤

当点位的刷新时间配置为特殊刷新时间（非“自定义”或“不刷新”）时，点位弹窗内点位的刷新时间一律显示为“不刷新”

### 实际结果

![image](https://github.com/user-attachments/assets/dd336fea-16cc-411c-8e08-3895029e90eb)
![image](https://github.com/user-attachments/assets/e5962532-f640-47bd-9584-2dd6de2006d2)

### 浏览器版本

Microsoft Edge 126.0.2592.68

### 系统版本

Windows 11 (23H2)

**Comment by Altermoe** [comment]
## 进度
已修复于 [Commit(dev) 3ca0aeb](https://github.com/kongying-tavern/map_register_v3/commit/3ca0aebad403b7a32f28dee0c7df2eb0106a9143)

## 定位问题
特殊刷新时间使用负数时间值进行编码，阅读友好输出函数未考虑此情况。
