### ISSUE TITLE
[Bug report] 附加信息字段显示配置与实际配置不一致

### ISSUE THREAD

**Issue by dango0911** [kongying-tavern/map_register_v3#133]
### 错误页面的链接

UAT

### 重现步骤

当【附加字段-分层层级】字段的属性为以下属性时：
``
{"underground":{"is_underground":true,"region_levels":[]}}
``
数据可以正常（即如上述属性）保存，但第二次打开编辑弹窗时，附加字段处显示配置为空（如下图）。
![image](https://github.com/user-attachments/assets/e6e6818d-c64c-4c94-b312-fb9d04d20605)

该 Bug 不影响实际数据和附加字段属性，仅影响显示。

### 浏览器版本

Microsoft Edge 126.0.2592.68

### 系统版本

Windows 11 (23H2)

**Comment by dango0911** [comment]
方才经进一步测试，如在第二次打开编辑弹窗时再次保存，则会以默认的字段配置（即“地面点位”）保存，所以某种程度上讲还是会影响到数据的，并不仅仅是外观问题
![1724990917588](https://github.com/user-attachments/assets/0d63064b-6fab-4dd1-a450-fbdb7bc44af0)

**Comment by Altermoe** [comment]
已修复于 [Commit c75cc81](https://github.com/kongying-tavern/map_register_v3/commit/c75cc8182d18eddb43eff62c372c3b88849c866f)
