### ISSUE TITLE
[Bug report] 登录态发生变化时会自动关闭打点页

### ISSUE THREAD

**Issue by dango0911** [kongying-tavern/map_register_v3#138]
### 错误页面的链接

正式环境

### 重现步骤

当用户的登录状态失效 / 手动退出登陆时，会导致打点页直接关闭，而不是 redirect to Login Page.

### 浏览器版本

Microsoft Edge 126.0.2592.68

### 系统版本

Windows 11 (23H2)

**Comment by Altermoe** [comment]
基于 [Commit 156d869](https://github.com/kongying-tavern/map_register_v3/commit/156d869411066d52d49043bd07fb775a939e227d) 修复
