### ISSUE TITLE
按照条件过滤点位

### ISSUE THREAD

**Issue by MomentDerek** [kongying-tavern/map_register_v3#41]

**Comment by lain887** [comment]
显示状态、地下地上。物品关联状态。
标题名称、描述内容。是否有图片。
计数、刷新时间

**Comment by Altermoe** [comment]
![Image](https://github.com/kongying-tavern/map_register_v3/assets/27633284/58cbdcf8-6dd4-43c1-9e10-5a6d1f44ccdf)
