### ISSUE TITLE
离线模式

### ISSUE THREAD

**Issue by mikezhuang2022** [kongying-tavern/map_register_v3#92]
## 用途
在后端炸了或者离线时可以正常使用后台地图。
## 触发方式
通过API请求钩子和用户token刷新来判断连接状态，也可以手动开关。
## 离线模式中可使用功能
地图查看，标记点位
## 备注
离线模式中对除刷新token外API屏蔽(防止一堆奇奇怪怪的BUG)。涉及后端读写的功能禁止使用

**Comment by Altermoe** [comment]
仅在开发模式下可用，对用户不可见，不能打点
