### ISSUE TITLE
关于开源的安全问题

### ISSUE THREAD

**Issue by jiazengp** [kongying-tavern/map_register_v3#95]
类似于 user,password 以及涉密的 .env 不应公开在开源仓库中。
<https://github.com/kongying-tavern/map_register_v3/blob/1c20f4e9c8d53a23cfe02cb3c48fe725033e7ce6/src/api/aliyun/drive.ts#L15>
<https://github.com/kongying-tavern/map_register_v3/blob/1c20f4e9c8d53a23cfe02cb3c48fe725033e7ce6/src/api/oauth/oauth.ts#L21>

**Comment by Altermoe** [comment]
感谢提醒，这确实是一个需要被考虑到的问题。
